apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server-deployment
  namespace: ashok
  labels:
    app: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: caannamalai/discovery-server:1.0.0
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: ashok
  labels:
    app: discovery-server
spec:
  type: LoadBalancer
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: discovery-server
