spring:
  application:
    name: discovery-server  # Name of the application
  config:
        import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

server:
  port: 8761  
eureka:
  instance:
    hostname: localhost 
  client:
    registerWithEureka: false 
    fetchRegistry: false  
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  

logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO

---
spring:
  config:
    activate:
      on-profile: docker  # Activation based on 'docker' profile
    import: configserver:http://34.122.230.187:8888/  # Correct Config Server URL for Docker

server:
  port: 8761  

eureka:
  instance:
    hostname: localhost  
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
