spring:
  application:
    name: discovery-server  # Name of the application
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://34.122.230.187:8888/}  # Use correct Config Server URL

server:
  port: 8761  # Port for Discovery Server

eureka:
  instance:
    hostname: localhost  # Instance hostname
  client:
    registerWithEureka: false  # Standalone mode
    fetchRegistry: false  # No need to fetch registry
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # Eureka server URL

logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO

---
spring:
  config:
    activate:
      on-profile: docker  # Activation based on 'docker' profile
    import: configserver:http://34.122.230.187:8888/  # Correct Config Server URL for Docker

server:
  port: 8761  # Ensure consistent port

eureka:
  instance:
    hostname: localhost  # Instance hostname
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
