apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: discovery-server

on:
  push:
    branches:
      - '**'

jobs:
  Checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
  Build:
    needs: Checkout
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: Build 
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install -DskipTests=true

  SonarAnalysisan:
    needs: Build
    steps:
      - uses: cloudbees-io/sonarqube-sast-scan-code@v1
        name: Scan
        kind: scan
        with:
          server-url: https://sonarqube.cb-demos.io
          username: admin
          password: admin123
          language: Java

      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        name: Scan 2
        kind: scan
        with:
          language: JAVA

      - uses: cloudbees-io/findsecbugs-sast-scan-code@v1
        name: Scan with Find Security Bugs
        kind: scan
        with:
          language: LANGUAGE_JAVA

      - uses: sbatchelder-cba/sonarqube-cba@v0.0.3
        name: Scan GP
        with:
          project-key: discovery-server
          token: 20e414018be1508e8a472229e7ec07da1a13cfa1

  
  DeployEc2:
    needs: SonarAnalysisan
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
          ls
      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install -DskipTests=true  

      - name: List built files
        uses: docker://alpine:latest
        run: |
          ls -l /cloudbees/workspace/target

      - name: Deploy to EC2
        uses: docker://alpine:latest
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          apk update
          apk add openssh-client
          echo "$EC2_SSH_KEY" > /cloudbees/workspace/ssh-key.pem
          chmod 600 /cloudbees/workspace/ssh-key.pem
          ls -l /cloudbees/workspace/target
          scp -o StrictHostKeyChecking=no -i /cloudbees/workspace/ssh-key.pem /cloudbees/workspace/target/spring-petclinic-discovery-server-1.0.0.jar ubuntu@54.174.48.42:/home/ubuntu/petclinic
          ssh -o StrictHostKeyChecking=no -i /cloudbees/workspace/ssh-key.pem ubuntu@54.174.48.42 "nohup java -jar /home/ubuntu/petclinic/spring-petclinic-discovery-server-1.0.0.jar > /home/ubuntu/petclinic/discovery-server.log 2>&1 &"


        