apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
      # Manual approval step
      - name: Manual approval
        uses: jenkins-automation/manual-approval-task:latest
        with:
          message: "Approve to continue the workflow"
          user: ${{ github.actor }}  # Replace with appropriate context if not GitHub
          password: ${{ secrets.MANUAL_APPROVAL_TOKEN }}  # Replace with your secret/token